spring:
  application:
    name: kidly
  profiles:
    default: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
