spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kidly
    username: kidly
    password: kidly
  jpa:
    properties:
      hibernate:
        format_sql: true

cors:
  allowed-origins: http://localhost:5173

logging:
  level:
    org.hibernate.SQL: debug
