name: CI

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 25

      - uses: gradle/actions/setup-gradle@v6

      # 컴파일, Checkstyle, ArchUnit, 테스트(Testcontainers)
      - name: Build
        run: ./gradlew build
